### ISSUE TITLE
[FE] back 버튼 이외 빈 공간에도 링크가 있습니다!

### ISSUE THREAD

**Issue by gitubanana** [leechan02/MySite#2]
## ⚠️ 어떤 버그인가요 ?
디자인이 아주 멋진 사이트 잘 보았습니다!
다만, 제가 찾은 불편함을 설명드리기 위해 이슈를 올리게 되었습니다.
이게 버그인지 아닌지는 개발자님의 의도에 따라 다를 것 같습니다.
이게 만약 개발자님의 의도라면, 이슈를 닫아주시면 감사하겠습니다!

- [x] back 버튼 이외 빈 공간에도 링크가 있어, 클릭하면서 보기 어렵습니다.

## 📝 어떤 상황에서 발생하나요 ?
1. [프로젝트 상세 페이지](https://www.euiclee.com/ko/mysite) 클릭
2. back버튼 근처 빈 공간을 누르면, /로 페이지 이동

## 💡 기대했던 동작
- [x] back 버튼만 링크가 있어야 된다고 생각합니다.

제가 잘못 확인했을 수도 있으니, 개발자님의 리뷰가 필요합니다.
읽어주셔서 감사합니다!

##  📷 스크린샷
- **back버튼과 함께 빈 공간이 `a`태그로 감싸져 있어, 빈 공간에도 링크가 달려있습니다**
![image](https://github.com/user-attachments/assets/4f879d96-f95e-4161-abe3-4fbf4d5a4c1a)

**Comment by leechan02** [comment]
아하?

**Comment by gitubanana** [comment]
확인해주시면 감사하겠습니다!
저는 글자를 드래그하면서 보는 편인데, 그럴 때마다 /로 페이지가 이동해 불편함이 있었습니다.

**Comment by gitubanana** [comment]
버그가 아니라면, 의도를 알려주시면 감사하겠습니다!

**Comment by leechan02** [comment]
바로 고쳤습니다. 오류 맞습니다. 사랑합니다.

**Comment by gitubanana** [comment]
찾은 보람이 있네요!
바로 답변주셔서 감사합니다!

**Comment by leechan02** [comment]
버그가 발생한다면 언제든지 얼마든지 언제나 항상 상시 신고부탁드립니다.❤️

**Comment by leechan02** [comment]
저희 서비스를 애용해주셔서 감사합니다:)

**Comment by gitubanana** [comment]
ㅋㅋㅋ 감사합니다!
